### ISSUE TITLE
Problem running on Windows

### ISSUE THREAD

**Issue by oscarbg** [redcode-labs/VTSCAN#5]
python3 vtscan.py README.md
```
[*] Sent file to VT api
Traceback (most recent call last):
  File "vtscan.py", line 104, in <module>
    main()
  File "vtscan.py", line 43, in main
    resource_hash = resp.json()['resource']
  File "C:\Users\rtfss\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by wintrmvte** [comment]
This tool is not suited to run on Windows, but it should run without any errors. This issue is probably connected to the API timeout, or problem with JSON, as 'resource' value cannot be found. Closing now, if it appears again, I will re-open.
